channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.17
  - pandas=1.5.3
  - rpy2=3.5.11
  - scikit-learn
  - numpy
  - jupyter
  - statsmodels
  - notebook
  - matplotlib
  - seaborn
  - kivy
  - scipy
  - openpyxl
  - blas
  - xlrd
  - r-lavaan=0.6_15
  - r-polycor
  - r-psych
  - r-corrplot
  - r-devtools
